### ISSUE TITLE
Error uploading image

### ISSUE THREAD

**Issue by johanjq** [funador/react-image-upload#2]
Hi, I'm getting the following issue. Is there anything you can do to help me with this? Thanks a lot!
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0 
82 |   })
  83 | })
  84 | .catch(err => {
> 85 |   err.json().then(e => {
  86 |     this.toast(e.message, 'custom', 2000, toastColor)
  87 |     this.setState({ uploading: false })
  88 |   })

**Comment by funador** [comment]
If you push all of your code up to GH and send me a link I will take a look.  There is not enough context here to solve the problem at the moment.  Cheers.

**Comment by johanjq** [comment]
Hi, thank you so much for the reply. I managed to solve the problem. I just
had to restart the nodemon server. I'll use this code to my project, thank
you very much for your content and great tutorials

Johan

**Comment by funador** [comment]
Welcome! Closing
