### ISSUE TITLE
Receive "Cannot GET /" message

### ISSUE THREAD

**Issue by cdoyle21** [funador/react-image-upload#4]
Hi,
Thanks for your tutorial so far, it has been very helpful. However, after running 'npm i && npm run dev' on the server, I get the message "Cannot GET /" in the browser.

In the console the error I receive is:

Refused to load the image 'http://localhost:3000/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

 Hopefully you can help.
Thanks again

**Comment by cdoyle88** [comment]
In my server .env file I had the PORT set to 3000. I've updated it to 8080 and it is now working as expected. 

Thanks

**Comment by cdoyle21** [comment]
In my server .env file I had the PORT set to 3000. I've updated it to 8080 and it is now working as expected.

Thanks
