### ISSUE TITLE
Images are uploaded to the server once they are selected from users' local machine

### ISSUE THREAD

**Issue by wahjay** [funador/react-image-upload#5]
Hi, I just read your repo and realize that images are instantly sent to the server once users select some images to upload. And then when the users click the remove image icon, they are not actually removed from the server. Is there a way to display the image on the browser first before sending to the server?

**Comment by funador** [comment]
Of course, anything is possible with JavaScript, but that is outside the scope of what I wanted to accomplish with this repo.  Feel free to fork and extend :)
